"""empty message

Revision ID: 354ffb16381d
Revises: 
Create Date: 2024-04-03 17:27:31.755936

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "354ffb16381d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "condition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("co2", sa.Float(), nullable=True),
        sa.Column("metan", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "temperature",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("condition_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("latitude", sa.Integer(), nullable=False),
        sa.Column("longitude", sa.Integer(), nullable=False),
        sa.Column("highest", sa.Float(), nullable=False),
        sa.Column("average", sa.Float(), nullable=False),
        sa.Column("lowest", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("temperature")
    op.drop_table("condition")
    # ### end Alembic commands ###
