"""empty message

Revision ID: 81c92811a49e
Revises: b6f1f3696338
Create Date: 2024-04-12 23:28:29.494994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c92811a49e'
down_revision: Union[str, None] = 'b6f1f3696338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordinate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Integer(), nullable=False),
    sa.Column('average', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predicted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ssp', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Integer(), nullable=False),
    sa.Column('highest', sa.Float(), nullable=True),
    sa.Column('average', sa.Float(), nullable=False),
    sa.Column('lowest', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('temperature')
    op.drop_table('condition')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('co2', sa.FLOAT(), nullable=True),
    sa.Column('metan', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temperature',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('condition_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('latitude', sa.INTEGER(), nullable=False),
    sa.Column('longitude', sa.INTEGER(), nullable=False),
    sa.Column('highest', sa.FLOAT(), nullable=False),
    sa.Column('average', sa.FLOAT(), nullable=False),
    sa.Column('lowest', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('predicted')
    op.drop_table('observed')
    op.drop_table('location')
    op.drop_table('coordinate')
    # ### end Alembic commands ###
