name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
    
    - name: Install dependencies
      run: |
        poetry install --no-interaction

    - name: Init Database
      run: |
        alembic upgrade head
    
    - name: Run tests
      run: |
        poetry run pytest tests/
        
    - name: Check code formatting with Black
      run: |
        poetry run black --check .